# configs/run/base.yaml
seed: 42
on_exist: skip   # /skip/overwrite/error
save_logits: true
save_predictions: true

project_root: ${oc.env:TENSAKU_ROOT,${hydra:runtime.cwd}}
outputs_root: ${run.project_root}/outputs
out_dir: null
data_dir: ${data.base_dir}

tag: init${split.n_train}_b${al.budget}_ep${train.epochs}
