# configs/run/debug.yaml
seed: 42
on_exist: overwrite
save_logits: true
save_predictions: true

project_root: ${oc.env:TENSAKU_ROOT,.}
outputs_root: ${run.project_root}/outputs
out_dir: null
data_dir: ${data.base_dir}

tag: debug_${split.tag}_b${al.budget}_r${al.rounds}_ep${train.epochs}
